// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ActualizarPaciente(arg1:models.Paciente):Promise<void>;

export function ActualizarTurno(arg1:models.Turno):Promise<void>;

export function BuscarPacientes(arg1:string):Promise<Array<models.Paciente>>;

export function CambiarEstadoTurno(arg1:number,arg2:string):Promise<void>;

export function CrearPaciente(arg1:models.Paciente):Promise<void>;

export function CrearTurno(arg1:models.Turno):Promise<void>;

export function EliminarPaciente(arg1:number):Promise<void>;

export function EliminarTurno(arg1:number):Promise<void>;

export function EmitirEvento(arg1:string,arg2:any):Promise<void>;

export function GetConfiguracion():Promise<models.Configuracion>;

export function GetHistorialPaciente(arg1:number):Promise<Array<models.Turno>>;

export function GetPaciente(arg1:number):Promise<models.Paciente>;

export function GetTurno(arg1:number):Promise<models.Turno>;

export function GetTurnosDelDia(arg1:string):Promise<models.AgendaDia>;

export function GuardarConfiguracion(arg1:models.Configuracion):Promise<void>;
