// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActualizarPaciente(arg1) {
  return window['go']['main']['App']['ActualizarPaciente'](arg1);
}

export function ActualizarTurno(arg1) {
  return window['go']['main']['App']['ActualizarTurno'](arg1);
}

export function BuscarPacientes(arg1) {
  return window['go']['main']['App']['BuscarPacientes'](arg1);
}

export function CambiarEstadoTurno(arg1, arg2) {
  return window['go']['main']['App']['CambiarEstadoTurno'](arg1, arg2);
}

export function CrearPaciente(arg1) {
  return window['go']['main']['App']['CrearPaciente'](arg1);
}

export function CrearTurno(arg1) {
  return window['go']['main']['App']['CrearTurno'](arg1);
}

export function EliminarPaciente(arg1) {
  return window['go']['main']['App']['EliminarPaciente'](arg1);
}

export function EliminarTurno(arg1) {
  return window['go']['main']['App']['EliminarTurno'](arg1);
}

export function EmitirEvento(arg1, arg2) {
  return window['go']['main']['App']['EmitirEvento'](arg1, arg2);
}

export function GetConfiguracion() {
  return window['go']['main']['App']['GetConfiguracion']();
}

export function GetHistorialPaciente(arg1) {
  return window['go']['main']['App']['GetHistorialPaciente'](arg1);
}

export function GetPaciente(arg1) {
  return window['go']['main']['App']['GetPaciente'](arg1);
}

export function GetTurno(arg1) {
  return window['go']['main']['App']['GetTurno'](arg1);
}

export function GetTurnosDelDia(arg1) {
  return window['go']['main']['App']['GetTurnosDelDia'](arg1);
}

export function GuardarConfiguracion(arg1) {
  return window['go']['main']['App']['GuardarConfiguracion'](arg1);
}
